// src/ffi/bridge.rs
//
// cxx bridge definitions.
//
// This module is compiled ONLY when the `cxx-bridge` Cargo feature is enabled
// (i.e. during the hybrid Windows build).  On any other host the module is
// still syntactically present but the `#[cxx::bridge]` macro is not expanded.
//
// ABI strategy choice — cxx vs. extern "C"
// ─────────────────────────────────────────
// cxx is used here because:
//   • It generates both the Rust glue and the C++ shim from a single source
//     of truth, eliminating header/declaration drift.
//   • It enforces that string data crosses the boundary as `&str` / `CxxString`
//     — not as raw `*const c_char` — preventing use-after-free bugs.
//   • It provides compile-time type checking on both sides of the boundary.
//
// We use cxx for `EncodingMapper` and `utf_convert` because their interfaces
// involve only types that cxx supports:
//   – `i32`  (maps to `int32_t` / `int`)
//   – `&str` (maps to `rust::Str`)
//   – `&[u8]` (maps to `rust::Slice<uint8_t>`)
//   – `u32`  (maps to `uint32_t`)
//
// The `BufferState` / `FileManager` types are NOT bridged here because they
// depend on Win32 `HANDLE` and `FILETIME` types that cxx cannot represent.
// Those are wrapped in hand-written `extern "C"` stubs in `raw.rs`.
//
// Each function exposed here has a corresponding doc-comment explaining
// which C++ function it replaces and why it is placed at this boundary.

// The `#[cfg]` guard prevents the macro from being expanded on hosts that
// do not have a C++ compiler available (e.g. the Linux CI runner).
#[cfg(feature = "cxx-bridge")]
#[cxx::bridge(namespace = "npp_buffer")]
pub mod ffi_impl {
    // ── Functions exported from Rust to C++ ──────────────────────────────────
    //
    // C++ signature (generated by cxx):
    //
    //   namespace npp_buffer {
    //     int32_t encoding_get_from_index(int32_t index);
    //     int32_t encoding_get_index_from(int32_t encoding);
    //     int32_t encoding_get_from_string(rust::Str alias);
    //     uint32_t detect_encoding_from_bom(rust::Slice<const uint8_t> buf);
    //   }
    extern "Rust" {
        /// Return the Windows code-page integer for the given 0-based menu
        /// index.  Replaces `EncodingMapper::getEncodingFromIndex`.
        fn encoding_get_from_index(index: i32) -> i32;

        /// Return the 0-based menu index for a given code-page integer.
        /// Replaces `EncodingMapper::getIndexFromEncoding`.
        fn encoding_get_index_from(encoding: i32) -> i32;

        /// Return the code-page integer for an IANA / MIME alias string.
        /// Replaces `EncodingMapper::getEncodingFromString`.
        ///
        /// Note: The C++ callers pass `const char*`; cxx translates that to
        /// `rust::Str` automatically when calling this function.
        fn encoding_get_from_string(alias: &str) -> i32;

        /// Inspect the first bytes of a file buffer and return the `UniMode`
        /// discriminant (as `u32`) of the detected encoding.
        /// Returns `u32::MAX` when no BOM was found.
        ///
        /// Replaces `Utf8_16_Read::determineEncodingFromBOM`.
        fn detect_bom(buf: &[u8]) -> u32;
    }
}

// ── Free functions referenced by the bridge ──────────────────────────────────
//
// These are plain Rust free functions that the cxx `extern "Rust"` block
// points to.  They are thin wrappers around the real implementations in
// `encoding_mapper` and `utf_convert`.

use crate::encoding_mapper::EncodingMapper;
use crate::utf_convert::detect_encoding_from_bom;

/// See `EncodingMapper::get_encoding_from_index`.
pub fn encoding_get_from_index(index: i32) -> i32 {
    EncodingMapper::get_encoding_from_index(index)
}

/// See `EncodingMapper::get_index_from_encoding`.
pub fn encoding_get_index_from(encoding: i32) -> i32 {
    EncodingMapper::get_index_from_encoding(encoding)
}

/// See `EncodingMapper::get_encoding_from_string`.
pub fn encoding_get_from_string(alias: &str) -> i32 {
    EncodingMapper::get_encoding_from_string(alias)
}

/// Return the `UniMode` discriminant for the encoding detected from a BOM, or
/// `u32::MAX` if no BOM was found.
pub fn detect_bom(buf: &[u8]) -> u32 {
    detect_encoding_from_bom(buf)
        .map(|mode| mode as u32)
        .unwrap_or(u32::MAX)
}
